name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against
          fetch-depth: 0
      - name: Set ssh-agent # Apparently it creates the ~/.ssh folder
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_UI_PRIVATE_KEY }}
      - name: Register remote servers to known_hosts
        run: |
          echo ${{secrets.SSH_UI_KNOWN_HOST}} >> ~/.ssh/known_hosts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: Set Node JS version
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: 'Install Dependencies'
        run: npm ci
      - name: Setup K8s context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: 'Setup Helm'
        uses: azure/setup-helm@v3
        with:
          version: 3.9.1
      - name: 'Nx build'
        run: npx nx affected --target=deploy --docker-tag=${GITHUB_SHA} --api-domain=${{ secrets.API_DOMAIN }} --api-email=${{ secrets.API_EMAIL }} --ui-url=https://${{ secrets.UI_DOMAIN }} --project-name={project.name}
        env:
          INPUT_PUSH: true
          SSH_UI_USER: ${{ secrets.SSH_UI_USER }}
          SSH_UI_HOST: ${{ secrets.SSH_UI_HOST }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # issue: https://github.com/nx-tools/nx-tools/issues/327
          UI_DOMAIN: ${{ secrets.UI_DOMAIN }}
          UI_SSL_EMAIL: ${{ secrets.UI_SSL_EMAIL }}
          INPUT_BUILD_ARGS: "NX_API_URL=https://${{ secrets.API_DOMAIN }}" # issue: https://github.com/nx-tools/nx-tools/issues/350
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}