name: CI

on: ['pull_request']

jobs:
  build:
    name: Code linting & testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: Set Node JS version
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Nx commands'
        run: |
          npx nx affected --target=lint
          npx nx affected --target=test
